### ISSUE TITLE
pick an actual name for this first Rally study

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/rally-study-01#43]

**Comment by magorlick** [comment]
I set up an internal survey [here](https://mozilla.slack.com/archives/G018GLCKAN6/p1617209750183400).  Sounds like the consensus is to keep the name of the study in line with the user's goals and more specific.   We have tentatively picked "Your Time Online & Doom Scrolling", however we should consider our GTM positioning and final technical details for this name.  @javaun , I would like your feedback on our final selection.

**Comment by javaun** [comment]
I'm fine with that name for GTM. You might want to put it in quotes since it's Jargon. We should probably also define it in the initial copy for clarity. And maybe drop the ampersand

_Your Time Online and "Doom Scrolling"_

Here's a definition:

_Doomscrolling and doomsurfing are new terms referring to the tendency to continue to surf or scroll through bad news, even though that news is saddening, disheartening, or depressing._

Source: [M-W](https://www.merriam-webster.com/words-at-play/doomsurfing-doomscrolling-words-were-watching#:~:text=Doomscrolling%20and%20doomsurfing%20are%20new,saddening%2C%20disheartening%2C%20or%20depressing.) (it's legit!)

**Comment by hamilton** [comment]
thanks, closing this issue
